spring.application.name=examen
spring.datasource.url=jdbc:mysql://localhost:3306/examen
spring.datasource.username=root
spring.datasource.password=Monserrath

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect